added github issue templates
NevronAI/metisfl pull request #24
Opened 2023-07-13 05:47 UTC by panoskyriakis

Created issue templates for the following:

1. Bug report
2. Feature Request
3. Documentation
4. Question

Correct render not verified; must merge to main.

2023-07-13 16:02 UTC, stripeli requested changes

2023-07-13 16:02 UTC, stripeli commented on .github/ISSUE_TEMPLATE/config.yaml
> +    url: team@nevron.ai
Why this email? Have we created an alias?

2023-07-13 16:02 UTC, stripeli commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +description: Submit a proposal or request for a new feature in prompttools!
What is a prompt tool? Be more specific.

2023-07-13 16:02 UTC, stripeli commented on .github/ISSUE_TEMPLATE/feature_request.yaml
> +        A clear and concise description of the feature proposal
Put period at the end of the sentence.

2023-07-13 16:02 UTC, stripeli commented on .github/ISSUE_TEMPLATE/question.yaml
> +description: Discuss or ask question about how to use prompttools and what the best practice may be.
Type: ask questions on how to ...
Similar to the comment earlier. Which prompt tool are we referring to?

2023-07-13 18:06 UTC, panoskyriakis commented on .github/ISSUE_TEMPLATE/config.yaml
> +    url: team@nevron.ai
Yes

2023-07-15 13:36 UTC, dstripelis approved these changes

2023-07-15 13:37 UTC, stripeli approved these changes

2023-07-15 13:38 UTC, merged